src/com/booksaw/betterTeams/integrations/TeamPlaceholders.java

Add a placeholder, `%betterteams_online%`, which returns the number of online members of their team. Resolves #110

add online placeholder

---

src/com/booksaw/betterTeams/commands/HelpCommand.java

only run help for relevant command

---

src/com/booksaw/betterTeams/commands/presets/TeamSelectSubCommand.java
src/com/booksaw/betterTeams/commands/teama/InviteTeama.java

fix hardcoding needPlayer in some teama commands

---

src/com/booksaw/betterTeams/events/MCTeamManagement.java

fix suffix space

---

messages.yml
src/com/booksaw/betterTeams/Main.java
src/com/booksaw/betterTeams/commands/teama/TeleportTeama.java

Please do a deep review to ensure this is all setup correctly... I may have missed something or set something up in a way that you don't like because I'm unfamiliar with your system.
Also I'm not sure how you feel about wild-card imports.. Didn't notice it changed before committing and pushing but my IntelliJ is configured to use them automatically if using all classes inside of the import, which you are. It makes sense to me but I know that some developers don't like using them. Up to you if you wanna keep that.

Add teleporting teams support from issue #242

---

src/com/booksaw/betterTeams/commands/teama/TeleportTeama.java

I was bored and this was easy.

Implement feature as requested in #269

---

src/main/java/com/booksaw/betterTeams/events/InventoryManagement.java

Please implement this ASAP
This screenshot is with 80 online players on a dedicated 5800X

Update InventoryManagement.java (80% Performance improvement)

---

src/main/java/com/booksaw/betterTeams/integrations/ZKothManager.java
src/main/resources/plugin.yml

This fixes the integration with zKoth to make it work with it's API in the newest version.
Before merging this PR, the updated API will first have to be merged into the BetterTeams-Deadens repo.
Here is the PR for that: https://github.com/booksaw/BetterTeams-Deadends/pull/1

Fix zKoth integration

---

src/main/resources/config.yml

Config file is moved to another folder

fix wrong repo link

---

src/main/java/com/booksaw/betterTeams/database/api/Database.java

A temporary solution to the SQL connection timeout issue reported in #460. I would recommend looking into connection pooling as a more permanent solution.

Fixed SQL connection timeout issue.

---

src/main/java/com/booksaw/betterTeams/commands/team/DemoteCommand.java
src/main/java/com/booksaw/betterTeams/database/api/Database.java

Fixed the ClassCastException reported in #465.

465 fix class cast ex

---

pom.xml
src/main/java/com/booksaw/betterTeams/Main.java
src/main/java/com/booksaw/betterTeams/commands/teama/CreateHoloTeama.java
src/main/java/com/booksaw/betterTeams/commands/teama/RemoveHoloTeama.java
src/main/java/com/booksaw/betterTeams/integrations/hologram/DHHologramManager.java
src/main/java/com/booksaw/betterTeams/integrations/hologram/HDHologramManager.java
src/main/java/com/booksaw/betterTeams/integrations/hologram/HologramManager.java

Adds DecentHolograms support as requested in #357.

DecentHolograms Support

---

src/main/java/com/booksaw/betterTeams/integrations/placeholder/provider/LevelPlaceholderProvider.java

Fixed the %betterteams_level% placeholder.

---

src/main/java/com/booksaw/betterTeams/database/BetterTeamsDatabase.java
src/main/java/com/booksaw/betterTeams/database/api/Database.java
src/main/java/com/booksaw/betterTeams/team/storage/storageManager/SQLStorageManager.java
src/main/java/com/booksaw/betterTeams/team/storage/team/SQLTeamStorage.java

I can't test it right now. So yeah I wouldn't merge it is just yet, but you can look at the code and look if you find something that I overlooked.

Fix Memory leak c: [Tested]

---

src/main/resources/nl.yml

Added dutch language support file

---

src/main/java/com/booksaw/betterTeams/commands/team/SetOwnerCommand.java

Resolves the issue where an offline player was attempting to be cast as a CommandSender object. Closes #531

Fixes bug with /team setowner

---

.gitignore

Updates .gitignore to ignore common IntelliJ created files.

Adds IntelliJ files to gitignore

---

src/main/java/com/booksaw/betterTeams/commands/teama/LeaveTeama.java

Allows specification of an offline player on `/teama leave`.

OfflinePlayer on /teama leave

---

src/main/resources/config.yml

Changed "palyer" to "player" in `config.yml`

Simple typo fix

---

src/main/java/com/booksaw/betterTeams/Team.java
src/main/java/com/booksaw/betterTeams/Warp.java
src/main/java/com/booksaw/betterTeams/commands/team/chest/ChestClaimCommand.java
src/main/java/com/booksaw/betterTeams/commands/teama/chest/ChestClaimTeama.java
src/main/java/com/booksaw/betterTeams/team/AllyRequestComponent.java
src/main/java/com/booksaw/betterTeams/team/AllySetComponent.java
src/main/java/com/booksaw/betterTeams/team/BanSetComponent.java
src/main/java/com/booksaw/betterTeams/team/ChestClaimComponent.java
src/main/java/com/booksaw/betterTeams/team/LocationSetComponent.java
src/main/java/com/booksaw/betterTeams/team/MemberSetComponent.java
src/main/java/com/booksaw/betterTeams/team/SetTeamComponent.java
src/main/java/com/booksaw/betterTeams/team/TeamPlayerSetComponent.java
src/main/java/com/booksaw/betterTeams/team/UuidSetComponent.java
src/main/java/com/booksaw/betterTeams/team/WarpSetComponent.java
src/main/java/com/booksaw/betterTeams/team/storage/storageManager/SQLStorageManager.java
src/main/java/com/booksaw/betterTeams/team/storage/storageManager/SeparatedYamlStorageManager.java

I noticed that a lot of Lists were used for allies and chests etc, but it didn't really matter what order this was in. Just that it was available.
I changed this now to use `Set`'s which should improve the performance a little bit.
Plus-side: it didn't need much refactoring.
FYI difference in timings:
``` 
ArrayList add: 3.823 ms
HashSet add: 3.026 ms
ArrayList contains: 1.756.988 ms
HashSet contains: 3.222 ms
ArrayList remove: 168.611 ms
HashSet remove: 4.121 ms
```
The addition is quite similar in performance, but the check and removal are much, much faster.
Please let me know if you would need some adjustments here.

Replacing List with Set.

---

src/main/java/com/booksaw/betterTeams/Team.java

For whatever reason, the functionality of TeamDisallowedPvPEvent was removed.
I simply readded the functionality of this event

Readded TeamDisallowedPvPEvent functionality

---

src/main/java/com/booksaw/betterTeams/Team.java
src/main/java/com/booksaw/betterTeams/commands/team/AllyCommand.java
src/main/java/com/booksaw/betterTeams/commands/team/NeutralCommand.java
src/main/java/com/booksaw/betterTeams/commands/teama/AllyTeama.java
src/main/java/com/booksaw/betterTeams/commands/teama/NeutralTeama.java
src/main/java/com/booksaw/betterTeams/events/ChestManagement.java

Removing lots of `getID()` to clean up the code

---

.github/workflows/maven-build.yml
src/main/java/com/booksaw/betterTeams/commands/team/WarpCommand.java
src/main/java/com/booksaw/betterTeams/commands/team/WarpsCommand.java
src/main/java/com/booksaw/betterTeams/commands/teama/WarpTeama.java
src/main/java/com/booksaw/betterTeams/cost/CommandCost.java
src/main/java/com/booksaw/betterTeams/customEvents/post/PostCreateTeamEvent.java
src/main/java/com/booksaw/betterTeams/customEvents/post/PostDemotePlayerEvent.java
src/main/java/com/booksaw/betterTeams/customEvents/post/PostDisbandTeamEvent.java
src/main/java/com/booksaw/betterTeams/customEvents/post/PostLevelupTeamEvent.java
src/main/java/com/booksaw/betterTeams/customEvents/post/PostPlayerJoinTeamEvent.java
src/main/java/com/booksaw/betterTeams/customEvents/post/PostPlayerLeaveTeamEvent.java
src/main/java/com/booksaw/betterTeams/customEvents/post/PostPromotePlayerEvent.java
src/main/java/com/booksaw/betterTeams/customEvents/post/PostPurgeEvent.java
src/main/java/com/booksaw/betterTeams/customEvents/post/PostTeamColorChangeEvent.java
src/main/java/com/booksaw/betterTeams/customEvents/post/PostTeamDepositEvent.java
src/main/java/com/booksaw/betterTeams/customEvents/post/PostTeamNameChangeEvent.java
src/main/java/com/booksaw/betterTeams/customEvents/post/PostTeamTagChangeEvent.java
src/main/java/com/booksaw/betterTeams/customEvents/post/PostTeamWithdrawEvent.java
src/main/java/com/booksaw/betterTeams/database/api/TableBuilder.java

* Revert some isEmpty() changes because StringBuilder::isEmpty didn't exist till JDK15
* Explicitly mentioning of classes for the docstrings where the qualifier couldn't be found.

refactor: clean up IDE reported errors

---

dependency-reduced-pom.xml
pom.xml
src/main/java/dev/ceymikey/exceptions/FailedEndpointException.java
src/main/java/dev/ceymikey/exceptions/InjectionFailureException.java
src/main/java/dev/ceymikey/injection/DiscordPayload.java
src/main/java/dev/ceymikey/injection/EmbedBuilder.java
src/main/java/dev/ceymikey/json/JsonArray.java
src/main/java/dev/ceymikey/json/JsonElement.java
src/main/java/dev/ceymikey/json/JsonObject.java

I'd like to contribute a WebhookHandler implementation that avoids dependency issues with the previous approach. I noticed it was relying on `org.json.JSONArray` which isn't available at runtime (causing `NoClassDefFoundError`).
My implementation:
- Removes dependency on external JSON libraries by using the one that is already loaded by minecraft
- Uses only `org.apache.http.client` classes that are confirmed available at runtime

Inline Ceymikey's code

---

src/main/java/com/booksaw/betterTeams/Team.java
src/main/java/com/booksaw/betterTeams/commands/team/NeutralCommand.java
src/main/java/com/booksaw/betterTeams/commands/teama/NeutralTeama.java
src/main/java/com/booksaw/betterTeams/customEvents/CreateTeamEvent.java
src/main/java/com/booksaw/betterTeams/customEvents/DemotePlayerEvent.java
src/main/java/com/booksaw/betterTeams/customEvents/DisbandTeamEvent.java
src/main/java/com/booksaw/betterTeams/customEvents/LevelupTeamEvent.java
src/main/java/com/booksaw/betterTeams/customEvents/PlayerJoinTeamEvent.java
src/main/java/com/booksaw/betterTeams/customEvents/PlayerLeaveTeamEvent.java
src/main/java/com/booksaw/betterTeams/customEvents/PromotePlayerEvent.java
src/main/java/com/booksaw/betterTeams/customEvents/TeamColorChangeEvent.java
src/main/java/com/booksaw/betterTeams/customEvents/TeamNameChangeEvent.java
src/main/java/com/booksaw/betterTeams/customEvents/TeamSendMessageEvent.java
src/main/java/com/booksaw/betterTeams/customEvents/TeamTagChangeEvent.java
src/main/java/com/booksaw/betterTeams/customEvents/post/PostTeamDepositEvent.java
src/main/java/com/booksaw/betterTeams/customEvents/post/PostTeamWithdrawEvent.java
src/main/java/dev/ceymikey/injection/DiscordPayload.java

@svaningelgem These are the fixes I think are needed, let me know if you see anything that looks like it will break as you have been looking at the code more than me recently

Assorted bug fixes

---

.github/dependabot.yml

I don't know if you want this, but I like to keep my dependencies up-to-date.
This bot helps you do that by opening PRs with the updates.

introducing dependency upgrades
