booksaw/BetterTeams

config.yml
- Fixed https://github.com/booksaw/BetterTeams/blob/master/config.yml#L313
- Fixed https://github.com/booksaw/BetterTeams/blob/master/config.yml#L302
- Fixed https://github.com/booksaw/BetterTeams/blob/master/config.yml#L425
- Fixed https://github.com/booksaw/BetterTeams/blob/master/config.yml#L81
=> Fixed #264

src/main/java/com/booksaw/betterTeams/integrations/placeholder/TeamPlaceholders.java
As this placeholder is special and does not require any team or teamplayer, I added it in an if statement before TeamPlaceholderService use. Fixes #479
=> Add %inteam% placeholder support

src/main/java/com/booksaw/betterTeams/database/BetterTeamsDatabase.java, src/main/java/com/booksaw/betterTeams/database/api/Database.java, src/main/java/com/booksaw/betterTeams/team/storage/convert/YamlToSql.java, src/main/java/com/booksaw/betterTeams/team/storage/storageManager/SeparatedYamlStorageManager.java
- Changes **echest** column from a _VARCHAR_ to a _TEXT_ due to too long strings to save.
- Now uses StringUtils#replaceOnce() instead of string#replaceFirst() due to the automatic removal of escaping chars by this method.
- Some optimizations
=> Fixes sql errors

pom.xml, src/main/java/com/booksaw/betterTeams/Team.java, src/main/java/com/booksaw/betterTeams/customEvents/TeamMessageEvent.java, src/main/java/com/booksaw/betterTeams/customEvents/TeamPreMessageEvent.java
I would like to propose the addition of a TeamPreMessageEvent and TeamMessageEvent to allow third-party developers to more accurately detect, amend and cancel team messages. 
This pull request contains the following amendments:
- Created a new class TeamPreMessageEvent which contains all the components of a team message and allows modifiable components to be modified before a team message is dispatched.
- Created a new class TeamMessageEvent which serves as a read-only notification that a message has been sent for monitoring purposes (such as third-party spy or audit plugins). 
- Implemented TeamPreMessageEvent in the existing Team class under method `Team#sendMessage(TeamPlayer, String)` by creating the event, providing it with the message components, dispatching the event, parsing all …
=> Add a TeamPreMessageEvent and TeamMessageEvent to the API

src/main/java/com/booksaw/betterTeams/integrations/placeholder/TeamPlaceholderOptionsEnum.java, src/main/java/com/booksaw/betterTeams/integrations/placeholder/provider/AdminsPlaceholderProvider.java, src/main/java/com/booksaw/betterTeams/integrations/placeholder/provider/DefaultMembersPlaceholderProvider.java, src/main/java/com/booksaw/betterTeams/integrations/placeholder/provider/OwnersPlaceholderProvider.java
Adds placeholders to get the member(s) at a specific rank. If there are multiple with the same rank then they are all returned separated by commas. Closes #537
- `%betterteams_owners%` - Gets the owner(s) for the team that the viewing player is a member of
- `%betterteams_static_owners_Supers%` - Gets the owner(s) for the team "Supers"
- `%betterteams_admins%` - Gets the admin(s) for the team that the viewing player is a member of
- `%betterteams_static_admins_Supers%` - Gets the admin(s) for the team "Supers"
- `%betterteams_defaultmembers%` - Gets the default member(s) for the team that the viewing player is a member of
- `%betterteams_static_defaultmembers_Supers%` - Gets the default member(s) for the team "Supers"
=> Adds placeholders to get members at a specific rank

src/main/java/com/booksaw/betterTeams/events/ChatManagement.java, src/main/resources/config.yml
Adds prefixes to go from the global chat to either the team or ally chat. These prefixes are all configurable and the prefix to go from the team chat or ally chat to the global chat has also been updated to be configurable. Resolves #314
=> Adds chat prefix to go from global to team or ally chat

src/main/java/com/booksaw/betterTeams/integrations/placeholder/TeamPlaceholderOptionsEnum.java, src/main/java/com/booksaw/betterTeams/integrations/placeholder/provider/PositionBalPlaceholderProvider.java, src/main/java/com/booksaw/betterTeams/integrations/placeholder/provider/PositionMembersPlaceholderProvider.java, src/main/java/com/booksaw/betterTeams/integrations/placeholder/provider/PositionScorePlaceholderProvider.java
Adds placeholders to get the numerical position in the three existing ranked lists. Currently does not handle number formatting i.e. 5120109 would be returned with no commas or periods denoting 1000s. Closes #538
- `positionscore` - Current position of the team ranked by score
- `positionbal` - Current position of the team ranked by balance
- `positionmembers` - Current position of the team ranked by amount of members
=> Adds placeholders to get current positions

dependency-reduced-pom.xml, pom.xml, src/main/java/com/booksaw/betterTeams/Main.java, src/main/java/com/booksaw/betterTeams/Team.java, src/main/java/com/booksaw/betterTeams/commands/team/DisbandCommand.java, src/main/java/com/booksaw/betterTeams/commands/teama/DisbandTeama.java, src/main/java/com/booksaw/betterTeams/customEvents/CreateTeamEvent.java, src/main/java/com/booksaw/betterTeams/customEvents/DisbandTeamEvent.java, src/main/java/com/booksaw/betterTeams/integrations/WorldGuardManagerV7.java, src/main/java/com/booksaw/betterTeams/team/TeamManager.java
- Allows developers to catch players responsible for creating or disbanding teams.
- Updates a few dependencies so the project can be compiled on fresh machines.
- Replaces a Java 11+ Nullable import to restore Java 8 compatibility.
- Fixes a spelling error in one class name.
=> Expose player in certain events and cleanup

src/main/java/com/booksaw/betterTeams/commands/team/DisbandCommand.java
Simplifies the team disband confirmation logic by removing redundant code paths.
No change in behavior
=> refactor: streamline team disband confirmation flow

src/main/java/com/booksaw/betterTeams/ConfigManager.java, src/main/java/com/booksaw/betterTeams/commands/team/InfoCommand.java, src/main/java/com/booksaw/betterTeams/database/api/TableBuilder.java, src/main/java/com/booksaw/betterTeams/team/storage/convert/FlatFileToYaml.java, src/main/java/com/booksaw/betterTeams/team/storage/storageManager/SQLStorageManager.java
StringBuilder - chain append calls instead of concatenation
Stream - use Files.newInputStream/newOutputStream instead of the FileInputStream
Array creation - don't create a big array if all it needs is the type
__Background info:__
Here's why the `Files` methods (second snippet) tend to perform better:
1. **Operating System Optimizations**: The NIO-based `Files` methods can take advantage of operating system-specific optimizations. They're designed to use native I/O operations where possible.
2. **Memory-Mapped Files**: The NIO package can potentially use memory-mapped files internally, which provides faster access by mapping a file directly to memory.
3. **Channel-Based Operations**: Behind the scenes, `Files` methods use `FileChannel` which can perform more efficient block transfers …
=> perf: Several performance improvements

pom.xml, src/main/java/com/booksaw/betterTeams/TeamPlayer.java, src/main/java/com/booksaw/betterTeams/Utils.java, src/main/java/com/booksaw/betterTeams/team/TeamPlayerSetComponent.java
This PR refactors the TeamPlayerSetComponent class to use Java 8 streaming interfaces instead of traditional for-loops.
Key changes:
- Replace all for-loops with stream operations
- Used method references where appropriate
- Added comments
=> refactor: Convert TeamPlayerSetComponent to use streaming API

src/main/java/com/booksaw/betterTeams/message/MessageManager.java
```
[19:26:20 WARN]: [BetterTeams] Plugin BetterTeams v4.10.0 generated an exception while executing task 51898
java.lang.NullPointerException: Cannot invoke "org.bukkit.command.CommandSender.sendMessage(String)" because "sender" is null
at BetterTeams-4.10.0.jar/com.booksaw.betterTeams.message.MessageManager.sendMessage(MessageManager.java:191) ~[BetterTeams-4.10.0.jar:?]
at BetterTeams-4.10.0.jar/com.booksaw.betterTeams.Team$1.run(Team.java:742) ~[BetterTeams-4.10.0.jar:?]
at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[paper-1.21.jar:1.21-106-3a47518]
at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.21.jar:1.21-106-3a47518]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22 …
```
=> Received a NPE, so adding checks for sender being null here.

src/main/java/com/booksaw/betterTeams/database/TableName.java, src/main/resources/config.yml
I think a configurable table prefix is ​​a good addition for that niche where you may have only one database but use it on multiple servers in a network.
=> Adding 'database.tablePrefix' to config and using it in TableName class

src/main/java/com/booksaw/betterTeams/customEvents/post/PostTeamSendMessageEvent.java, src/main/java/com/booksaw/betterTeams/util/WebhookHandler.java
This solves immediately the duplicate message sending too.
The problem was in Team.java#963:
```
TeamSendMessageEvent teamSendMessageEvent = new TeamSendMessageEvent(this, sender, message, format, prefix, recipients);
TeamPreMessageEvent deprecatedPreTeamMessageEvent = new TeamPreMessageEvent(this, sender, message, format, prefix, recipients);
Bukkit.getPluginManager().callEvent(teamSendMessageEvent);
Bukkit.getPluginManager().callEvent(deprecatedPreTeamMessageEvent);
```
And:
```
public class TeamPreMessageEvent extends TeamSendMessageEvent {
```
So the message was received twice.
I now changed this interface to use the post-messages (at that point in time we know it's not cancelled for sure).
This solves the duplicate team messages too.
Closes #756
=> Use post-events when posting messages to discord

src/main/java/com/booksaw/betterTeams/Team.java, src/main/java/com/booksaw/betterTeams/events/ChestManagement.java, src/main/java/com/booksaw/betterTeams/team/TeamManager.java
I haven't fully tested it, as I think other commands are affected, the hopper event detects the chests just fine. I hope I haven't missed something when rewriting the TeamManager module.
EDIT: forgot the spark links
In the first two tests I put ingots in a chest, copied it with NBTs and filled a Shulker, then repeated a couple of times
Before: https://spark.lucko.me/d26dJrbWom
**After**
Purpur: https://spark.lucko.me/TOe22g9VkT
Spigot: https://spark.lucko.me/VUI1Xp7jEP (Spigot was absolutely dying, the 0.08mspt are caused by the server overloading)
Spigot (removed the heavy items): https://spark.lucko.me/0hGguS542m (this is the actual value)
=> Optimize onHopper for both Spigot and Paper users

src/main/java/com/booksaw/betterTeams/text/Formatter.java
Including the shadow color tag resolver in the PermissiveFormatter class causes it to fail to initialize correctly if the server is Paper and is below version 1.21.4 (my best guess). I did not foresee this and should be removed unless an nms trick is implemented.
=> Remove shadow color tag resolver from PermissiveFormatter for compatibility with Paper servers below 1.21.4

pom.xml
Because junit needs to be bumped together...
The added maven repository is necessary for a transient dependency from decentholograms.
Without it, it will fail to build because of the cache.
I think somewhere along the line they (cryptomin.XSeries) changed from common/old-bukkit/new-bukkit structure to just 1 jar file and uploaded this to maven central. And it's in the cache of github actions.
So adding maven central as the first repository forces the build to look there first and update its cache.
=> chore: bumping versions

pom.xml, src/main/java/com/booksaw/betterTeams/Main.java, src/main/java/com/booksaw/betterTeams/integrations/LuckPermsManager.java, src/main/resources/plugin.yml, wiki/docs/05-dependencies/Dependencies.md, wiki/docs/05-dependencies/LuckPerms.md
contexts:
| Context Key                   | Description                                                                 | Example Value(s)                         |
|-------------------------------|-----------------------------------------------------------------------------|------------------------------------------|
| `bt_inteam`                   | Checks if a player is in any team.                                          | `true`, `false`                          |
| `bt_rank`                     | The player's rank within their team.                                        | `owner`, `admin`, `default`              |
| `bt_teamchat`                 | Current chat mode the player is using.                                      | `Team Chat`, `Ally Chat`, `Global Chat`  |
| `bt_level` …
=> initial LuckPerms context support

src/main/java/com/booksaw/betterTeams/Main.java
**Problem Explanation**:
After plugin reload (via the `reload()` method, usually triggered by `/teama reload`), if an online player left the server and rejoined, the plugin couldn't send messages to them (likely new players logging in after reload had the same issue).
**Root Cause**:
As far as I understood, the issue was with `BukkitAudiences`, which wasn't fully closed after reload and held onto the old plugin's data. In `onEnable()`, since `adventure` was never null, a new one wasn't created. The old instance could only send to console or to players whose pre-reload data was still valid.
**Summary**:
Reloading without server restart breaks Adventure features; full restart fixes it.
No errors in logs, but `audience.player(recipient).sendMessage(message)` silently fails for players. …
=> fix messages not sending after reload

src/main/java/com/booksaw/betterTeams/Main.java, src/main/java/com/booksaw/betterTeams/TeamPlayer.java, src/main/java/com/booksaw/betterTeams/events/HomeAnchorManagement.java, src/main/java/com/booksaw/betterTeams/team/MemberSetComponent.java
Make "anchor.ignoreObsidianAnchorRespawn" and "anchor.ignoreBedRespawn" actually work. HomeAnchorManagement should now be properly disabled and re-enabled when /teama reload is run.
=> HomeAnchorManagement fixes
